conformer: true
audio:
  chunk_size: 352800
  dim_f: 1024
  dim_t: 256
  hop_length: 441
  n_fft: 2048
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.0
model:
  dim: 256
  depth: 6
  stereo: true
  num_stems: 4
  time_conformer_depth: 1
  freq_conformer_depth: 1
  freqs_per_bands: !!python/tuple
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 12
    - 12
    - 12
    - 12
    - 12
    - 12
    - 12
    - 12
    - 24
    - 24
    - 24
    - 24
    - 24
    - 24
    - 24
    - 24
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 48
    - 128
    - 129
  dim_head: 64
  heads: 8
  attn_dropout: 0
  ff_dropout: 0
  flash_attn: true
  dim_freqs_in: 1025
  stft_n_fft: 2048
  stft_hop_length: 512
  stft_win_length: 2048
  stft_normalized: false
  mask_estimator_depth: 2
  multi_stft_resolution_loss_weight: 1.0
  multi_stft_resolutions_window_sizes: !!python/tuple
    - 4096
    - 2048
    - 1024
    - 512
    - 256
  multi_stft_hop_size: 147
  multi_stft_normalized: false
  mlp_expansion_factor: 2
  ff_mult: 4
  conv_expansion_factor: 2
  conv_kernel_size: 31
  use_torch_checkpoint: false
  skip_connection: false
  sage_attention: false
training:
  batch_size: 2
  gradient_accumulation_steps: 1
  grad_clip: 0.0
  instruments:
    - drums
    - bass
    - other
    - vocals
  patience: 3
  reduce_factor: 0.95
  target_instrument: null
  num_epochs: 1000
  num_steps: 1000
  q: 0.95
  coarse_loss_clip: false
  ema_momentum: 0.999
  optimizer: adamw
  lr: 1.0e-05
  other_fix: false
  use_amp: true
optimizer1:
  muon_group:
    lr: 0.001
    weight_decay: 0.0
    momentum: 0.95
  adam_group:
    lr: 0.0001
    weight_decay: 0.0
    betas:
      - 0.9
      - 0.99
    eps: 1.0e-08
augmentations:
  enable: true
  loudness: true
  loudness_min: 0.5
  loudness_max: 1.5
  mixup: true
  mixup_probs: !!python/tuple
    - 0.2
    - 0.02
    - 0.002
    - 0.0002
    - 2.0e-05
  mixup_loudness_min: 0.5
  mixup_loudness_max: 1.5
  mp3_compression_on_mixture: 0.1
  mp3_compression_on_mixture_bitrate_min: 32
  mp3_compression_on_mixture_bitrate_max: 320
  mp3_compression_on_mixture_backend: lameenc
  all:
    channel_shuffle: 0.5
    random_inverse: 0.1
    random_polarity: 0.5
  vocals:
    pitch_shift: 0.1
    pitch_shift_min_semitones: -5
    pitch_shift_max_semitones: 5
    seven_band_parametric_eq: 0.1
    seven_band_parametric_eq_min_gain_db: -9
    seven_band_parametric_eq_max_gain_db: 9
    tanh_distortion: 0.1
    tanh_distortion_min: 0.1
    tanh_distortion_max: 0.7
  bass:
    pitch_shift: 0.1
    pitch_shift_min_semitones: -2
    pitch_shift_max_semitones: 2
    seven_band_parametric_eq: 0.1
    seven_band_parametric_eq_min_gain_db: -3
    seven_band_parametric_eq_max_gain_db: 6
    tanh_distortion: 0.1
    tanh_distortion_min: 0.1
    tanh_distortion_max: 0.5
  drums:
    pitch_shift: 0.1
    pitch_shift_min_semitones: -5
    pitch_shift_max_semitones: 5
    seven_band_parametric_eq: 0.1
    seven_band_parametric_eq_min_gain_db: -9
    seven_band_parametric_eq_max_gain_db: 9
    tanh_distortion: 0.1
    tanh_distortion_min: 0.1
    tanh_distortion_max: 0.6
  other:
    pitch_shift: 0.1
    pitch_shift_min_semitones: -4
    pitch_shift_max_semitones: 4
    gaussian_noise: 0.1
    gaussian_noise_min_amplitude: 0.001
    gaussian_noise_max_amplitude: 0.015
    time_stretch: 0.1
    time_stretch_min_rate: 0.8
    time_stretch_max_rate: 1.25
inference:
  chunk_size: 882000
  batch_size: 1
  dim_t: 801
  num_overlap: 2
  normalize: false
