audio:
  sample_rate: 24000
inference:
  batch_size: 1
  num_overlap: 2
model:
  above_freq: 300.0
  architecture: conv_tasnet_stft
  batch_size: 55
  beta1: 0.5
  beta2: 0.9
  bn_chan: 256
  continual_train: true
  db_normalize: false
  ema: true
  encoder_activation: null
  entity: carson2050
  epochs: 200
  eps: 1.0e-08
  ff_activation: relu
  gradient_clip: null
  hid_chan: 1024
  load_ema_online_model: false
  lr_decay_gamma: 0.5
  mask_act: linear
  max_n_src: 4
  min_n_src: 2
  mixed_precision: false
  mixture_consistency: mixture_consistency
  multi_spec_loss_log_scale: false
  n_blocks: 6
  n_filter: 512
  n_kernel: 512
  n_nodes: 1
  n_repeats: 4
  n_src: 2
  nb_workers: 10
  nfft: 2048
  ngpus_per_node: 1
  nhop: 512
  no_mask: false
  no_mask_residual: false
  part_of_data: null
  patience: 50
  pitch_formant_augment_prob: 0.4
  port: null
  quiet: false
  rank: 0
  reduced_training_data_ratio: 1.0
  same_song_ratio: 0.2
  sample_rate: 24000
  seq_dur: 3.0
  skip_chan: 256
  sr_input_res: false
  sr_out_mix_consistency: false
  srnet: orig
  start_from_best: true
  sweep: false
  target: vocals
  unison_prob: 0.3
  use_ema_model: true
  use_wandb: true
  weight_decay: 1.0e-06
  world_size: 1
training:
  instruments:
    - vox_1
    - vox_2
  target_instrument: null
  use_amp: true
