audio:
  chunk_size: 352800
  dim_f: 1024
  dim_t: 256
  hop_length: 441
  min_mean_abs: 0.0
  n_fft: 2048
  num_channels: 2
  sample_rate: 44100
augmentations:
  all:
    channel_shuffle: 0.5
    random_inverse: 0.1
    random_polarity: 0.5
  enable: true
  loudness: true
  loudness_max: 1.5
  loudness_min: 0.5
  mixup: true
  mixup_loudness_max: 1.5
  mixup_loudness_min: 0.5
  mixup_probs: !!python/tuple
  - 0.2
  - 0.02
inference:
  batch_size: 1
  dim_t: 256
  num_overlap: 2
model:
  attn_dropout: 0
  depth: 6
  dim: 384
  dim_freqs_in: 1025
  dim_head: 64
  ff_dropout: 0
  flash_attn: true
  freq_transformer_depth: 1
  heads: 8
  linear_transformer_depth: 0
  mask_estimator_depth: 2
  mlp_expansion_factor: 4
  multi_stft_hop_size: 147
  multi_stft_normalized: false
  multi_stft_resolution_loss_weight: 1.0
  multi_stft_resolutions_window_sizes: !!python/tuple
  - 4096
  - 2048
  - 1024
  - 512
  - 256
  num_bands: 60
  num_stems: 4
  sample_rate: 44100
  skip_connection: false
  stereo: true
  stft_hop_length: 441
  stft_n_fft: 2048
  stft_normalized: false
  stft_win_length: 2048
  time_transformer_depth: 1
  use_torch_checkpoint: false
training:
  augmentation: false
  augmentation_loudness: false
  augmentation_loudness_max: 0
  augmentation_loudness_min: 0
  augmentation_loudness_type: 1
  augmentation_mix: false
  augmentation_type: null
  batch_size: 1
  coarse_loss_clip: false
  ema_momentum: 0.999
  grad_clip: 0
  gradient_accumulation_steps: 1
  instruments:
  - drums
  - bass
  - other
  - vocals
  lr: 1.0e-05
  num_epochs: 2
  num_steps: 3
  optimizer: adam
  other_fix: false
  patience: 2
  q: 0.95
  reduce_factor: 0.95
  target_instrument: null
  use_amp: true
  use_mp3_compress: false
